### ISSUE TITLE
space between lines

### ISSUE THREAD

**Issue by TCH69** [13-CF/aFetch#13]
![2020-10-04-183419_378x348_scrot](https://user-images.githubusercontent.com/44942508/95014357-77be5c00-0670-11eb-8ca5-317507b9dcde.png)
Everything is fine, but there's space between the lines.

**Comment by 13-CF** [comment]
Hi, I may have fixed it but please let me know if it still does this.

**Comment by TCH69** [comment]
![2020-10-04-191751_634x356_scrot](https://user-images.githubusercontent.com/44942508/95015321-60826d00-0676-11eb-815a-4482a5f65283.png)
It's kinda fixed now but something's missing.

**Comment by 13-CF** [comment]
Hi, this is because I accidentally pushed a custom config.h
You can fix it by changing the value for the *TEXT values. Deleting the second set and removing the comments on the first set should fix it. After this you can recompile it.

`/*
#define USERTEXT    "       USER"
#define DISROTEXT   "     DISTRO"
#define KERNELTEXT  "     KERNEL" 
#define UPTIMETEXT  "     UPTIME"
#define SHELLTEXT   "      SHELL"
#define PACKAGETEXT "       PKGS"
*/

// For icons to display correctly, a nerd font may be required 

#define USERTEXT    "     "
#define DISROTEXT   "     "
#define KERNELTEXT  "     " 
#define UPTIMETEXT  "     "
#define SHELLTEXT   "     "
#define PACKAGETEXT "     " `

Also, I see the value for SHELL is set to local. What is the output from `echo $SHELL`?

**Comment by TCH69** [comment]
`echo $SHELL` prints out `/usr/local/bin/zsh`.

**Comment by 13-CF** [comment]
Ok, I will have to fix the `shell()` function to have support for shells in `/usr/local/bin` then, as it isn't meant to display this. Currently it only supports shells in `/bin` and `/usr/bin`. 

Did you manage to get the missing text to display?

**Comment by TCH69** [comment]
No, It just show me `local`. Also, the issue is fixed now, I'll mark this issue as closed.
