### ISSUE TITLE
license clarification, gplv3 only or plus?

### ISSUE THREAD

**Issue by 06kellyjac** [13-CF/afetch#73]
Just wanted to check if this project is licensed gplv3 only or does it follow the "or any later version" provision?

Thanks

**Comment by 13-CF** [comment]
Hi, I honestly wasn't too bothered about the license so I just went with the GPLv3 cause that's what other popular open source software uses.

I'm thinking of changing to the more permissive BSD or MIT license though, as I don't care what people do with the program. Thanks!

**Comment by 06kellyjac** [comment]
I personally don't mind which license the project uses, it's just someone was packaging it for `nixpkgs` and we distinguish between gplv3Only and gplv3Plus and I wanted us to get it right :slightly_smiling_face:

This page has a pretty good discription of many licenses (obviously with a bias towards GPL as it's the FSF) https://www.gnu.org/licenses/license-list.en.html
But GPLv3 is good if you want modifications made to the project to remain GPLv3 and made available to all.
If you don't want that then yeah I guess a different license would be better.

**Comment by astralchan** [comment]
Any update on this? At the moment, packaging should probably be done with `GPL-3.0-only` as the author doesn't specify in README, comments in source, or otherwise. If one is going to use the GNU General Public license, this really should be specified, it's a part of using the license: https://www.gnu.org/licenses/quick-guide-gplv3.html. See the section "New Compatible Licenses."
