### ISSUE TITLE
apt error when trying to count packages

### ISSUE THREAD

**Issue by SirCipherz** [13-CF/aFetch#9]
## Expected Behavior
Show the number of packages

## Actual Behavior
![Image](https://sircipherz.com/files/debian.png)

## Steps to Reproduce the Problem

  1. run the program

## Specifications

  - Version: 0216c9f
  - Platform: Debian 9

**Comment by 13-CF** [comment]
It's been a while since I've used a Debian based distribution, so I'm unfamiliar with the package management. I think `dpkg -l | wc -l` might work, so it should hopefully be fixed in the next commit. `dpkg --get-selections | wc -l` may also work.

Would you mind checking to see if they're both accurate, and what ones fastest?

**Comment by SirCipherz** [comment]
`dpkg -l | wc -l` and `dpkg --get-selections | wc -l` return different outputs

**Comment by 13-CF** [comment]
It should be fixed now, I've changed the command.
I've also set up docker, so it should be easier for me to test the program.
